# Generated by Django 4.2.4 on 2023-09-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['version_number'], 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
